name: "Build"

on:
  pull_request:
  push:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p elmPackages.elm-format --run "elm-format --validate client"
      - uses: cachix/cachix-action@v12
        with:
          name: planning-game
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build -A client -A server
      - run: nix-build -A docker
